# part 1: variables

 DISK_FILE        = disk.bin
 DISK_HOST        = 127.0.0.1
 DISK_PORT        = 1236
 DISK_BLOCK_NUM   = 65536
 DISK_BLOCK_LEN   =    16

# part 3: targets

 create-disk :
	@dd of=${DISK_FILE} if=/dev/zero count=${DISK_BLOCK_NUM} bs=${DISK_BLOCK_LEN}

inspect-disk :
	@hexdump -C ${DISK_FILE}

 launch-disk :
	@python device/disk.py --host=${DISK_HOST} --port=${DISK_PORT} --file=${DISK_FILE} --block-num=${DISK_BLOCK_NUM} --block-len=${DISK_BLOCK_LEN}
